version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/deploy-github-pages"
      - "/export-gradle-properties"
      - "/post-release"
      - "/pre-release"
      - "/release-notes" 
    schedule:
      interval: "weekly"
