name: 'Micronaut release notes action'
description: 'Updates a draft release notes on every PR merge'
inputs:
  token:
    description: 'GitHub token to authenticate the requests'  
    required: true
    default: ${{ github.token }}
  repository:
    description: 'Repository in org/repo format'
    required: true
    default: ${{ github.repository }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.repository }}    